# This file is hidden (.cpu_cpi_on_pr.yml) to minimize the number of runner minutes consumed.

name: "Pull Request CPU Tests"

on:
  pull_request:
    paths: # job only triggers when the PR changes files under megatron directory
      - "megatron/**"

jobs:
  run-tests:
    runs-on: ubuntu-22.04 # ubuntu-latest currently points to ubuntu-22.04 but 24.04 is in beta - recommend testing on 24.04 and then changing instead of using ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Run CPU tests
      uses: ./tests/cpu_tests
      with:
        target_test_ref: ${{ github.event.pull_request.base.sha }}
