name: "Workflow Dispatch CPU Tests"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Target ref / SHA to run tests against'
        required: true
        default: 'main'

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Run CPU tests
      uses: ./tests/cpu_tests
      with:
        target_test_ref: ${{ inputs.ref }}
